apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: devopsproject
        image: devopsproject:latest
        ports:
        - containerPort: 80
        env:
        - name: ENV_VAR_NAME
          value: "value"

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort        # Changed to NodePort for local access
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001     # NodePort for accessing the service externally (optional)
  selector:
    app: my-app
